package com.ooustream.iptv.backup

import android.content.Context
import android.os.Environment
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import com.google.gson.Gson
import com.google.gson.JsonSyntaxException
import com.ooustream.iptv.data.local.dao.FavoriteDao
import com.ooustream.iptv.data.local.dao.SearchHistoryDao
import com.ooustream.iptv.data.local.dao.WatchProgressDao
import com.ooustream.iptv.data.repository.CredentialStore
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.withContext
import java.io.File
import java.security.KeyStore
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class BackupService @Inject constructor(
    private val favoriteDao: FavoriteDao,
    private val watchProgressDao: WatchProgressDao,
    private val searchHistoryDao: SearchHistoryDao,
    private val credentialStore: CredentialStore,
    @ApplicationContext private val context: Context
) {

    private val gson = Gson()

    companion object {
        private const val KEYSTORE_ALIAS = "ooustream_backup_key"
        private const val GCM_TAG_LENGTH = 128
        private const val GCM_IV_LENGTH = 12
    }

    private fun getOrCreateKey(): SecretKey {
        val keyStore = KeyStore.getInstance("AndroidKeyStore")
        keyStore.load(null)

        keyStore.getEntry(KEYSTORE_ALIAS, null)?.let { entry ->
            return (entry as KeyStore.SecretKeyEntry).secretKey
        }

        val keyGenerator = KeyGenerator.getInstance(
            KeyProperties.KEY_ALGORITHM_AES, "AndroidKeyStore"
        )
        keyGenerator.init(
            KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .build()
        )
        return keyGenerator.generateKey()
    }

    private fun encrypt(data: ByteArray): ByteArray {
        val key = getOrCreateKey()
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv // 12 bytes generated by Cipher
        val encrypted = cipher.doFinal(data)
        // Prepend IV to ciphertext so decrypt can recover it without separate storage
        return iv + encrypted
    }

    private fun decrypt(data: ByteArray): ByteArray {
        val key = getOrCreateKey()
        val iv = data.copyOfRange(0, GCM_IV_LENGTH)
        val ciphertext = data.copyOfRange(GCM_IV_LENGTH, data.size)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH, iv))
        return cipher.doFinal(ciphertext)
    }

    suspend fun exportBackup(): Result<File> = withContext(Dispatchers.IO) {
        runCatching {
            val favorites = favoriteDao.getAllFavorites().first()
            val watchProgress = watchProgressDao.getAllProgress().first()

            val backupData = BackupData(
                version = BackupData.CURRENT_VERSION,
                timestamp = System.currentTimeMillis(),
                favorites = favorites,
                watchProgress = watchProgress
            )

            val json = gson.toJson(backupData)
            val encryptedBytes = encrypt(json.toByteArray(Charsets.UTF_8))

            val dateFormat = SimpleDateFormat("yyyyMMdd_HHmmss", Locale.US)
            val fileName = "ooustream_backup_${dateFormat.format(Date())}.ooubackup"

            val dir = context.getExternalFilesDir(Environment.DIRECTORY_DOCUMENTS)
                ?: throw IllegalStateException("External files directory is not available")

            if (!dir.exists()) {
                dir.mkdirs()
            }

            val file = File(dir, fileName)
            file.writeBytes(encryptedBytes)
            file
        }
    }

    /**
     * Import a legacy v1 unencrypted backup from a raw JSON string.
     * Used by [BackupFragment] when the user pastes JSON text manually.
     */
    suspend fun importBackup(input: String): Result<Int> = withContext(Dispatchers.IO) {
        runCatching {
            val backupData = try {
                gson.fromJson(input, BackupData::class.java)
            } catch (e: JsonSyntaxException) {
                throw IllegalArgumentException("Invalid backup file format", e)
            }

            requireNotNull(backupData) { "Backup data is empty" }

            if (backupData.version > BackupData.CURRENT_VERSION) {
                throw IllegalArgumentException(
                    "Backup version ${backupData.version} is newer than supported version ${BackupData.CURRENT_VERSION}. Please update the app."
                )
            }

            restoreBackupData(backupData)
        }
    }

    /**
     * Import a v2 encrypted backup from raw bytes read from a `.ooubackup` file.
     * The key lives in the Android KeyStore bound to this device — backups cannot
     * be decrypted on a different device.
     */
    suspend fun importBackupEncrypted(encryptedBytes: ByteArray): Result<Int> = withContext(Dispatchers.IO) {
        runCatching {
            val decryptedJson = decrypt(encryptedBytes).toString(Charsets.UTF_8)
            val backupData = try {
                gson.fromJson(decryptedJson, BackupData::class.java)
            } catch (e: JsonSyntaxException) {
                throw IllegalArgumentException("Failed to decrypt backup or invalid format", e)
            }

            requireNotNull(backupData) { "Backup data is empty" }

            if (backupData.version > BackupData.CURRENT_VERSION) {
                throw IllegalArgumentException(
                    "Backup version ${backupData.version} is newer than supported version ${BackupData.CURRENT_VERSION}. Please update the app."
                )
            }

            restoreBackupData(backupData)
        }
    }

    private suspend fun restoreBackupData(backupData: BackupData): Int {
        clearAllData()

        var restoredCount = 0

        backupData.favorites.forEach { favorite ->
            favoriteDao.insert(favorite)
            restoredCount++
        }

        backupData.watchProgress.forEach { progress ->
            watchProgressDao.upsert(progress)
            restoredCount++
        }

        return restoredCount
    }

    suspend fun clearAllData() = withContext(Dispatchers.IO) {
        favoriteDao.clearAll()
        watchProgressDao.clearAll()
        searchHistoryDao.clear()
        credentialStore.clear()
    }
}
